FROM python:3.10-slim
WORKDIR /code
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
RUN addgroup --system appgroup && adduser --system appuser --ingroup appgroup
USER appuser
ENTRYPOINT ["/entrypoint.sh"]
